config/routes.rb
CTO::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :schedules

  resources :reviews

  get "orders/new"
  get "orders/create"
  get "orders/index"
  devise_for :users
  get "services/create"

  scope '(:locale)' do
    resources :ctos do
      resources :services
      resources :orders
      resources :schedules
    end
  end

  root 'ctos#index'
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :service


  #Let's add callback to update associated schedules before saving a date
  before_save {|record|
    # If record was approved than we have to update schedules
    if !record.new_record? && record.status=='approved' && record.confirmationDate?

      #Let's store current date
      record.confirmationDate = DateTime.current

      #Got a _service to retrive cto_id
      _service = Service.find(record.service_id)

      #Insert new schedule load based on order data
      _schedule = Schedule.new
      _schedule.date=Date.current
      _schedule.start=record.plannedDate
      #Schedule by default - 1 hour 60*60
      _schedule.end=_schedule.start + 60*60
      _schedule.cto_id = _service.cto_id
      _schedule.save
    end

   # we need to remove busy schedule from cancelled record
   if record.status=='cancelled'
     Schedule.where(:date => record.plannedDate).destroy_all;
   end


  }

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  #Method to create new form
  def new
    @cto=Cto.find(params[:cto_id])

    # we need to get all services to evaluate and add them to the dropdown
    @services =@cto.services;

    #need to add info about checking the calendar and providing acceptable date range to fill.TODO: In perspective we need to create cache of predefined data and update it when order is approved.
    @schedules=Schedule.where('schedules.date=? AND cto_id=?',Date.current ,params[:cto_id])

    #Need to calcualte. We need to make a reverse about schedule making a suggestion according to current time on server.
    @events = []
    @schedules.each do |schedule|
      @events.push(Event.new(schedule.date, schedule.start, schedule.end))
    end

    #TODO: Let's restrict date selection for 2-3 days forward.User should be able to select only those dates
    @order = Order.new
    @order.plannedDate=Date.current
  end

  def create
    # TODO let's add logic to create an order with appropriate params.Save order and redirect to main cto page
    @cto=Cto.find (params[:cto_id])
    @service = Service.find(params[:selectedService])

    @order = Order.new

    #set order model parameters.Objects are stored as hashes.We don't need to have cae number
    #@order.carNumber=params[:order][:carNumber]
    @order.plannedDate=params[:order][:plannedDate] || Date.current

    @order.status='New'
    @order.requestDate=Date.current
    @order.user=current_user
    @order.service=@service

    @order.uniqueCode=SecureRandom.hex(10)
    @order.save

    #Show user his uniqueid and add appropriate params
    redirect_to cto_order_path :cto_id=>@cto.id,:id=>@order.id, :order => @order
  end

  #Let's show the unique number
  def show
    @order=Order.find(params[:id]);
  end


  def update
    #TODO: Add update functionality
  end

  def index
  #Get orders for particular cto based on input parameter.We will show them based on the status
  @orders= Order.joins(service: :cto).where('ctos.id' => params[:cto_id])
  end

end

class Event
  attr_accessor :date, :start, :end
  def initialize(date, startTime, endTime)
    @date=date
    @start=startTime
    @end=endTime
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/index.html.erb
<h1> Review the orders status for cto</h1>

<table>
  <caption>Замовлення по сто- треба додати форму для пошуку та фільтру замовлень по даті, статусу і сто </caption>
  <tr>
    <th>ID</th>
    <th>price</th>
    <th>request date</th>
    <th>confirmation date</th>
    <th>status</th>
    <th>plannedDate</th>
    <th>carNumber</th>
    <th>uniqueCode</th>
  </tr>
  <% @orders.each do |order| %>
      <tr>
        <td style="padding-left:10px"><%= order.id %></td>
        <td style="padding-left:10px"><%= order.price %></td>
        <td style="padding-left:10px"><%= order.requestDate %></td>
        <td style="padding-left:10px"><%= order.confirmationDate %></td>
        <td style="padding-left:10px"><%= order.status %></td>
        <td style="padding-left:10px"><%= order.plannedDate %></td>
        <td style="padding-left:10px"><%= order.carNumber %></td>
        <td style="padding-left:10px"><%= order.uniqueCode %></td>
      </tr>
  <% end %>
</table>

app/views/orders/new.html.erb
<h1>Замовити нову послугу. Вибір дати може здійснюватися тільки за наявності вільного часу. Це означає що варто створити можель де можна буде вибрати вільний час</h1>

<%= form_for [@cto,@order] do |ord| %>

    <p>
      <%=ord.label (:plannedDate) %>
      <%=ord.text_field :plannedDate %>

    </p>

    <p>

      <%= ord.label (:selectedService) %><br>
      <%= ord.select(:service, options_for_select(@services.map{|s| [s.description,s.id]}, @selectedService)) %>
    </p>

    <p>
       <%= label_tag(:selectedTime) %><br>
        <%= select_tag(:selectedTime, options_for_select(@events.map{|s| [s.start,s.start]}, @selectedTime)) %>
    </p>

    <p>
      <%= ord.submit :class => 'btn btn-lg btn-success' %>
    </p>
<% end %>

<script type="text/javascript">
    $("#order_plannedDate" ).datepicker();
    $("#order_plannedDate" ).datepicker( "option", "dateFormat","dd-mm-yy" );
    $("#order_plannedDate" ).datepicker('setDate', '<%=@plannedDate%>');
</script>

app/views/orders/show.html.erb
<div style="text-align: center">
<h1> Дякуємо за замовлення</h1>
</div>

<p>Ваш промокод для пред'явлення на мийці <%= @order.uniqueCode %></p>
<p>На вашу почтову адресу буде вислане повідомлення про підтвердження/або відхилення замовлення протягом 5-10 хвилин</p>
<p>Слід додати сюди ще інформацію про мийку, користувача який замовив послугу та кнопку повернення</p>
<span style="text-align:right"><%= link_to 'На головну', ctos_path, class: 'btn btn-default', style: 'font-size:10px' %></span>