config/routes.rb
CTO::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :schedules

  resources :reviews

  get "orders/new"
  get "orders/create"
  get "orders/index"
  devise_for :users
  get "services/create"

  scope '(:locale)' do
    resources :ctos do
      resources :services
      resources :orders
      resources :schedules
    end
  end

  root 'ctos#index'
end

app/models/cto.rb
class Cto < ActiveRecord::Base
  has_many :services
  has_many :schedules
  max_paginates_per 9
  # validates :name, presence: true
  # validates :description, presence: true
  # validates :address, presence: true
  # validates :contacts, presence: true
  # validates :schedule, presence: true
  geocoded_by :address
  after_validation :geocode
end

app/controllers/ctos_controller.rb
class CtosController < ApplicationController
  def new
  end

  #Create new CTO based on form parameters 1
  def create
    redirect_to ctos_path :myLocation=>params[:myLocation],:radius=>params[:radius], :page=>params[:page]
  end

  
   #Show CTO find by id param
  def show
    @cto = Cto.find(params[:id])
  end


  def numeric?(object)
    true if Float(object) rescue false
  end


   #Show all available CTO
  def index

    @currentLocation=params[:myLocation].to_s;
    @currentRadius=params[:radius].to_s;

     if params[:myLocation].to_s.empty? || params[:radius].to_s.empty?
        @ctos = Cto.all.page params[:page]

        #Set current data for search params
        @currentLocation='Ivano-Frankivsk';
        @currentRadius=2;

    else
     @ctos=Cto.near(params[:myLocation].to_s,params[:radius].to_s,:order => "distance",:units => :km).page params[:page];

     #Store search values as default


    end
   end

 # set paramerer time and store it between search
  def setAllowedTime
    @timeStorage=[]
    (1..23).each do |time|
      @timeStorage.push([time.to_s + ":00", time.to_s + ":00"])
    end
    @selectedTime = params[:requestTime].to_s
  end

  # set paramerer date and store it between search
  def setSearchDate
    @searchDate = params[:requestDate];

    if @searchDate.to_s.empty?
      @searchDate=Time.now.strftime("%d-%m-%Y");
    end
  end

  #Load object to put CTO data to edit
  def edit
    @cto = Cto.find(params[:id])
  end

  #Update edited data
  def update
    @cto = Cto.find(params[:id])
    if @cto.update(cto_params)
      redirect_to ctos_path
    else
      render 'edit'
    end
  end

  #Remove CTO from the database
  def destroy
    @cto = Cto.find(params[:id])
    @cto.destroy
    redirect_to ctos_path
  end


  #It's a special method to hack strong parameters
  private
  def cto_params
    params.require(:cto).permit(:name, :description, :address, :contacts,:schedule)
  end
end

app/helpers/ctos_helper.rb
module CtosHelper
end

app/views/ctos/edit.html.erb
<h1>Editing CTO data</h1>
 
<%= form_for :cto, url: cto_path(@cto), method: :patch do |ct| %>
  <% if @cto.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@cto.errors.count, "error") %> prohibited this CTO from being saved:</h2>
    <ul>
    <% @cto.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
      
    <% end %>
    </ul>
  </div>
 <% end %>
  
  <p>
    <%= ct.label :name %><br>
    <%= ct.text_field :name %>
  </p>
 
  <p>
    <%= ct.label :description %><br>
    <%= ct.text_area :description %>
  </p>
  
   <p>
    <%= ct.label :address %><br>
    <%= ct.text_area :address %>
  </p>
  
  <p>
    <%= ct.label :contacts %><br>
    <%= ct.text_area :contacts %>
  </p>
  
  <p>
    <%= ct.label :schedule %><br>
    <%= ct.text_area :schedule %>
  </p>
 
  <p>
    <%= ct.submit %>
  </p>
 
<% end %>
 

app/views/ctos/index.html.erb
<div class="navbar navbar-default">
  <div class="container container-fluid">
    <div class="navbar-header">
        <h1 style="color:white">Каталог мийок Івано-Франківська</h1>
    </div>
  </div>
</div>

<div style="padding:5px">
  <%= form_tag({:controller=>'ctos', :action=>'index',:method=> 'post'},{:class =>'navbar-form navbar-left',:role => 'search'}) do%>
    <div class="form-group">
      <span> <label for="currentRadius"><%=raw t('.myCurrentLocation')%></label><%= text_field_tag(:myLocation, @currentLocation,:id=>"currentLocation", :class=>"form-control") %></span>
      <label for="currentRadius"> В радіусі, км</label><%= text_field_tag(:radius, @currentRadius,:type=>"number", :id=>"currentRadius", :class=>"form-control") %>
      <%= button_tag(type: 'submit', class: 'form-control btn btn-primary',onClick:"ga('send', 'Search', 'Locations', 'click', $('#currentLocation').val(), 1);") do %>
        Пошук&nbsp;<span class="glyphicon glyphicon-search"></span>
      <%end %>
      </span>
    </div>
    <% end %>
</div>
<div class="container" id="main" style="float:left;width:100%">
  <div style="text-align: center">
    <%= paginate @ctos %>
  </div>
  <% @ctos.each_slice(3) do |ctoChunk|%>
         <div class="row">
             <% ctoChunk.each do |cto| %>
               <div class=" col-sm-4 col-md-4">
                 <div class="panel panel-primary">
                   <div class="panel-heading"><h3 class="panel-title"><%= cto.name %></h3></div>
                   <div class="panel-body">
                     <div><%= raw t('.address', address: cto.address) %></div>
                     <div><%= raw t('.contacts', contacts: cto.contacts) %></div>

                     <% if cto.has_attribute?("distance") %>
                         <div><%= raw t('.distance', distance: cto.distance)%></div>
                     <% end %>
                   </div>
                   <div class="panel-footer" style="text-align: right"></div>
                 </div>
               </div>
              <% end %>
         </div>
    <% end %>
  <div style="text-align: center">
    <%= paginate @ctos %>
  </div>
 </div>

app/views/ctos/new.html.erb
<div>Ввести дані для нової станції технічного обслуговування</div>
<%= form_for :cto, url: ctos_path do |ct| %>
  <p>
    <%= ct.label :name %><br>
    <%= ct.text_field :name %>
  </p>
 
  <p>
    <%= ct.label :description %><br>
    <%= ct.text_area :description %>
  </p>
  
   <p>
    <%= ct.label :address %><br>
    <%= ct.text_area :address %>
  </p>
  
  <p>
    <%= ct.label :contacts %><br>
    <%= ct.text_area :contacts %>
  </p>
  
  <p>
    <%= ct.label :schedule %><br>
    <%= ct.text_area :schedule %>
  </p>
 
  <p>
    <%= ct.submit 'Submit', :class => 'btn btn-lg btn-success' %>
  </p>
<% end %>

app/views/ctos/show.html.erb
<p>
  <strong>Назва:</strong>
  <%= @cto.name %>
</p>
 
<p>
  <strong>Опис:</strong>
  <%= @cto.description %>
</p>

<p>
  <strong>Адреса:</strong>
  <%= @cto.address %>
</p>

<p>
  <strong>Контакти:</strong>
  <%= @cto.contacts %>
</p>

<p>
  <strong>Розклад роботи:</strong>
  <%= @cto.schedule %>
</p>

<h2>Послуги які пропонує сервіс</h2>

<table class="table table-striped table-bordered table-condensed">
  <thead>
  <tr>
    <th>Опис послуги</th>
    <th>Вартість</th>
    <th>Операції</th>
  </tr>
  </thead>
  <tbody>
  <% @cto.services.each do |service| %>
      <tr>
        <td><%= service.description %></td>
        <td><%= service.price %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<h2>Відгуки про дану сто</h2>
<% @cto.services.each do |service| %>
    <hr>
    <p>Evaluated service:<%= service.description %></p>
    <% service.reviews.each do |review| %>
        <p>
          Description:<%= review.reviewText %>
        </p>

        <p>
          Mark:<%= review.mark %>
        </p>

    <% end %>
<% end %>

<%= link_to 'На головну', ctos_path %>